swagger: '2.0'
info:
  title: Dataset management backend API
  description: this is Swagger for the Dataset management backend
  version: 1.0
tags:
  - name: Dataset Part
    description: API for Dataset management
paths:
  /api/dataset:
    parameters:
    - in: header
      name: x-access-token
      schema:
        type: string
      required: true
    get:
      tags:
        - Dataset Part
      summary: Returns all dataset record from database.
      responses: 
        '200':
          description: OK


  /api/dataset/{dataset_id}:
    parameters:
    - in: header
      name: x-access-token
      schema:
        type: string
      required: true
    - name: dataset_id
      in: path
      description: ID of dataset to return
      required: true
      type: integer
      example: 1
      format: int64
    get:
      tags:
        - Dataset Part
      summary: Returns dataset record from dataset id.
      responses: 
        '200':
          description: OK

  /api/dataset/:
    post:
      tags:
        - Dataset Part
      summary: creates dataset record
      description: 'creates dataset record'
      operationId: uploadFile
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: header
          name: x-access-token
          schema:
            type: string
          required: true
        - name: dataset_question
          in: formData
          description: dataset question for create dataset
          required: true
          type: string
        - name: dataset_reply
          in: formData
          description: dataset reply for create dataset
          required: true
          type: string
        - name: admin_id
          in: formData
          description: admin id who creates dataset record
          required: true
          type: integer
        - name: dataset_image_upload
          in: formData
          description: file to upload
          required: false
          type: file
      responses:
        '200':
          description: OK

          


          